# ---------------------------------------------------------------------------- #
#           🚫✋ This Workflow is AutoInstalled - Don't edit manually          #
# ---------------------------------------------------------------------------- #
name: AutoInstall_Dependabot_Approve_Merge
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  # Only approve the bizcover-bot PR's. Cant use the fastify one as its only applicable for the dependabot user.
  autoapproveonly:
    runs-on: ubuntu-latest
    
    if: ${{ github.actor == 'bizcover-bot' }}
    steps:
      - name: Approve bizcover-bot PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  
  # Approve and merge the Depdendabot PR's
  autoapproveandmerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # Get metadata about the update types so it can be compared in other steps
      - name: Dependabot metadata 
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Approve and Merge if the Update Type was a Patch
        uses: fastify/github-action-merge-dependabot@v3
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }} 
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Only approve if the Update Type was anything except a Patch
        uses: fastify/github-action-merge-dependabot@v3 
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-patch' }} 
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          approve-only: true