# ---------------------------------------------------------------------------- #
#           🚫✋ This Workflow is AutoInstalled - Don't edit manually          #
# ---------------------------------------------------------------------------- #
name: BLAZE_TEST_TRIGGER

on:
  release:
    types: 
      - published

env:
  SYSTEMTESTS_REPOSITORY: BizCover/BizCover.Blaze.PlatformTests

jobs:
 SystemTests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Bizcover Actions
        uses: actions/checkout@v2
        with:
          repository: BizCover/BizCover.DevOps.Actions
          token: ${{ secrets.GH_TOKEN }}
          path: bizcover
      - name: System Tests Dispatch
        if: ${{ success() }}
        uses: ./bizcover/actions/repository-dispatch
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ env.SYSTEMTESTS_REPOSITORY }}
          event-type: platform-tests
          client-payload: '{"repository": "${{ github.repository }}", "version": "${{ github.event.release.tag_name }}"}'